#!/bin/bash

start_ubuntu(){
    if [[ "$1" == "-h" ]]; then
        echo "help"
    elif [[ "$1" == "o" ]]; then
        run_vnc
        get_offline
    elif [[ "$1" == "o-n" ]]; then
        run_vnc
        get_online
    elif [[ ! -z "$1" ]]; then
        echo "Invalid option. Use '-h' for help"
    else
        run_vnc
    fi
    return 0
}

run_vnc(){
    vncserver -kill -clean
    vncserver -useold -cleanstale
}

get_online(){
    bash /home/sakib/noVNC-1.4.0/utils/novnc_proxy --listen 6080 --vnc 5901
    ngrok http 6080
    return 0
}
get_offline(){
    bash /home/sakib/noVNC-1.4.0/utils/novnc_proxy --listen 6080 --vnc 5901
    return 0
}

# Call the custom command function with the provided arguments
start_ubuntu "$@"
